// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the Wails v3 service. It exposes auth and usage methods to the
 * frontend and implements ServiceStartup so it receives the app context.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as usage$0 from "./internal/usage/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetAuthStatus returns whether the Copilot provider has a valid credential.
 */
export function GetAuthStatus(): $CancellablePromise<$models.AuthStatus> {
    return $Call.ByID(14599403).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetCopilotUsage fetches GitHub Copilot usage through the provider adapter.
 */
export function GetCopilotUsage(): $CancellablePromise<usage$0.UsageReport | null> {
    return $Call.ByID(1026146656).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetUsage fetches usage data for a named provider.
 */
export function GetUsage(providerName: string): $CancellablePromise<usage$0.UsageReport | null> {
    return $Call.ByID(2234764926, providerName).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ListProviders returns the provider adapters currently wired into the app.
 */
export function ListProviders(): $CancellablePromise<string[]> {
    return $Call.ByID(4005662969).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * LogOut clears the stored credential for the Copilot provider and persists.
 */
export function LogOut(): $CancellablePromise<void> {
    return $Call.ByID(3752090883);
}

/**
 * PollGitHubLogin polls the token endpoint once. Returns true when the user
 * has approved (credential is stored and persisted), false when still pending,
 * and an error on fatal states (expired, denied, network error).
 */
export function PollGitHubLogin(deviceCode: string): $CancellablePromise<boolean> {
    return $Call.ByID(2136922628, deviceCode);
}

/**
 * StartGitHubLogin begins the OAuth device flow and returns the user-facing
 * code and URL. The caller should display these to the user, then poll with
 * PollGitHubLogin.
 */
export function StartGitHubLogin(): $CancellablePromise<$models.DeviceFlowState | null> {
    return $Call.ByID(2314178265).then(($result: any) => {
        return $$createType5($result);
    });
}

// Private type creation functions
const $$createType0 = $models.AuthStatus.createFrom;
const $$createType1 = usage$0.UsageReport.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $models.DeviceFlowState.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
