// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AuthStatus is returned to the frontend to describe the current auth state
 * for a provider.
 */
export class AuthStatus {
    /**
     * Creates a new AuthStatus instance.
     * @param {Partial<AuthStatus>} [$$source = {}] - The source object to create the AuthStatus.
     */
    constructor($$source = {}) {
        if (!("authenticated" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["authenticated"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["source"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuthStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AuthStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AuthStatus(/** @type {Partial<AuthStatus>} */($$parsedSource));
    }
}

/**
 * DeviceFlowState is returned to the frontend when starting GitHub login.
 */
export class DeviceFlowState {
    /**
     * Creates a new DeviceFlowState instance.
     * @param {Partial<DeviceFlowState>} [$$source = {}] - The source object to create the DeviceFlowState.
     */
    constructor($$source = {}) {
        if (!("deviceCode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deviceCode"] = "";
        }
        if (!("userCode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["userCode"] = "";
        }
        if (!("verificationURI" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["verificationURI"] = "";
        }
        if (!("expiresIn" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["expiresIn"] = 0;
        }
        if (!("interval" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["interval"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceFlowState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeviceFlowState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeviceFlowState(/** @type {Partial<DeviceFlowState>} */($$parsedSource));
    }
}
