// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

/**
 * AuthStatus is returned to the frontend to describe the current auth state
 * for a provider.
 */
export class AuthStatus {
    "authenticated": boolean;
    "source"?: string;

    /** Creates a new AuthStatus instance. */
    constructor($$source: Partial<AuthStatus> = {}) {
        if (!("authenticated" in $$source)) {
            this["authenticated"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuthStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): AuthStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AuthStatus($$parsedSource as Partial<AuthStatus>);
    }
}

/**
 * DeviceFlowState is returned to the frontend when starting GitHub login.
 */
export class DeviceFlowState {
    "deviceCode": string;
    "userCode": string;
    "verificationURI": string;
    "expiresIn": number;
    "interval": number;

    /** Creates a new DeviceFlowState instance. */
    constructor($$source: Partial<DeviceFlowState> = {}) {
        if (!("deviceCode" in $$source)) {
            this["deviceCode"] = "";
        }
        if (!("userCode" in $$source)) {
            this["userCode"] = "";
        }
        if (!("verificationURI" in $$source)) {
            this["verificationURI"] = "";
        }
        if (!("expiresIn" in $$source)) {
            this["expiresIn"] = 0;
        }
        if (!("interval" in $$source)) {
            this["interval"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceFlowState instance from a string or object.
     */
    static createFrom($$source: any = {}): DeviceFlowState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeviceFlowState($$parsedSource as Partial<DeviceFlowState>);
    }
}
