// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the Wails v3 service. It exposes auth and usage methods to the
 * frontend and implements ServiceStartup so it receives the app context.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as usage$0 from "./internal/usage/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetAuthStatus returns whether the Copilot provider has a valid credential.
 * @returns {$CancellablePromise<$models.AuthStatus>}
 */
export function GetAuthStatus() {
    return $Call.ByID(14599403).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetCopilotUsage fetches GitHub Copilot usage through the provider adapter.
 * @returns {$CancellablePromise<usage$0.UsageReport | null>}
 */
export function GetCopilotUsage() {
    return $Call.ByID(1026146656).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetUsage fetches usage data for a named provider.
 * @param {string} providerName
 * @returns {$CancellablePromise<usage$0.UsageReport | null>}
 */
export function GetUsage(providerName) {
    return $Call.ByID(2234764926, providerName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetVersion returns the build version for the current app binary.
 * @returns {$CancellablePromise<string>}
 */
export function GetVersion() {
    return $Call.ByID(1049863377);
}

/**
 * ListProviders returns the provider adapters currently wired into the app.
 * @returns {$CancellablePromise<string[]>}
 */
export function ListProviders() {
    return $Call.ByID(4005662969).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * LogOut clears the stored credential for the Copilot provider and persists.
 * @returns {$CancellablePromise<void>}
 */
export function LogOut() {
    return $Call.ByID(3752090883);
}

/**
 * PollGitHubLogin polls the token endpoint once. Returns true when the user
 * has approved (credential is stored and persisted), false when still pending,
 * and an error on fatal states (expired, denied, network error).
 * @param {string} deviceCode
 * @returns {$CancellablePromise<boolean>}
 */
export function PollGitHubLogin(deviceCode) {
    return $Call.ByID(2136922628, deviceCode);
}

/**
 * StartGitHubLogin begins the OAuth device flow and returns the user-facing
 * code and URL. The caller should display these to the user, then poll with
 * PollGitHubLogin.
 * @returns {$CancellablePromise<$models.DeviceFlowState | null>}
 */
export function StartGitHubLogin() {
    return $Call.ByID(2314178265).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.AuthStatus.createFrom;
const $$createType1 = usage$0.UsageReport.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $models.DeviceFlowState.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
