// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

/**
 * UsageReport is the normalized payload returned by provider adapters.
 */
export class UsageReport {
    "provider": string;
    "periodStart"?: string;
    "periodEnd"?: string;
    "retrievedAt": string;
    "metrics": { [_ in string]?: number };
    "metadata"?: { [_ in string]?: string };

    /** Creates a new UsageReport instance. */
    constructor($$source: Partial<UsageReport> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("retrievedAt" in $$source)) {
            this["retrievedAt"] = "";
        }
        if (!("metrics" in $$source)) {
            this["metrics"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UsageReport instance from a string or object.
     */
    static createFrom($$source: any = {}): UsageReport {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metrics" in $$parsedSource) {
            $$parsedSource["metrics"] = $$createField4_0($$parsedSource["metrics"]);
        }
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField5_0($$parsedSource["metadata"]);
        }
        return new UsageReport($$parsedSource as Partial<UsageReport>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
