// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * UsageReport is the normalized payload returned by provider adapters.
 */
export class UsageReport {
    /**
     * Creates a new UsageReport instance.
     * @param {Partial<UsageReport>} [$$source = {}] - The source object to create the UsageReport.
     */
    constructor($$source = {}) {
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["periodStart"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["periodEnd"] = undefined;
        }
        if (!("retrievedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["retrievedAt"] = "";
        }
        if (!("metrics" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: number }}
             */
            this["metrics"] = {};
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["metadata"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UsageReport instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UsageReport}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metrics" in $$parsedSource) {
            $$parsedSource["metrics"] = $$createField4_0($$parsedSource["metrics"]);
        }
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField5_0($$parsedSource["metadata"]);
        }
        return new UsageReport(/** @type {Partial<UsageReport>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
