// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {usage} from '../models';

export function GetAuthStatus():Promise<main.AuthStatus>;

export function GetCopilotUsage():Promise<usage.UsageReport>;

export function GetUsage(arg1:string):Promise<usage.UsageReport>;

export function ListProviders():Promise<Array<string>>;

export function LogOut():Promise<void>;

export function PollGitHubLogin(arg1:string):Promise<boolean>;

export function StartGitHubLogin():Promise<main.DeviceFlowState>;
