// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCopilotUsage() {
  return window['go']['main']['App']['GetCopilotUsage']();
}

export function GetUsage(arg1) {
  return window['go']['main']['App']['GetUsage'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListProviders() {
  return window['go']['main']['App']['ListProviders']();
}
