// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {usage} from '../models';

export function GetCopilotUsage():Promise<usage.UsageReport>;

export function GetUsage(arg1:string):Promise<usage.UsageReport>;

export function Greet(arg1:string):Promise<string>;

export function ListProviders():Promise<Array<string>>;
