// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAuthStatus() {
  return window['go']['main']['App']['GetAuthStatus']();
}

export function GetCopilotUsage() {
  return window['go']['main']['App']['GetCopilotUsage']();
}

export function GetUsage(arg1) {
  return window['go']['main']['App']['GetUsage'](arg1);
}

export function ListProviders() {
  return window['go']['main']['App']['ListProviders']();
}

export function LogOut() {
  return window['go']['main']['App']['LogOut']();
}

export function PollGitHubLogin(arg1) {
  return window['go']['main']['App']['PollGitHubLogin'](arg1);
}

export function StartGitHubLogin() {
  return window['go']['main']['App']['StartGitHubLogin']();
}
